/* ==========================================================================
 *   INCLUDE FILE NAME: app_priv.h
 * INCLUDE DESCRIPTION: sub-library private include file.
 *       CREATION DATE: 20181016
 *             AUTHORS: Fabrizio De Siati
 *        DESIGN ISSUE: None. 
 *
 *             HISTORY: See table below.
 * 
 * 16-Oct-2018 | Fabrizio De Siati | 0.0 |
 * Initial creation of this file.
 * 
 * ========================================================================== */

#ifndef APP_PRIV_H
#define APP_PRIV_H

/* ==========================================================================
 * INCLUDE: This file is generated by CMake for managing macro based source
 * code configuration. The HAVE_CONFIG_H macro is set into the CMakeLists.txt
 * project file.
 * ========================================================================== */
#ifdef HAVE_CONFIG_H
# include "BrokerTelegramBot_config.h"
#endif

#endif  // APP_PRIV_H
